project_id = "izspjvegxdfgkgibpyst"

[functions.popular-cppm-da-tabela-editar]
verify_jwt = false

[functions.popular-cppm-v2]
verify_jwt = false

[functions.corrigir-titulos-cppm]
verify_jwt = false

[functions.extrair-titulos-cppm-planalto]
verify_jwt = false

[functions.adicionar-titulos-cppm]
verify_jwt = false

[functions.corrigir-espacamento-cppm]
verify_jwt = false